name: Build Windows Binaries

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: setup deb822 repos
      run: |
        if [[ $ImageOS == "ubuntu24" ]]; then
          cat <<EOF > deb822sources
        Types: deb
        URIs: http://archive.ubuntu.com/ubuntu/
        Suites: noble
        Components: main restricted universe
        Architectures: amd64
            
        Types: deb
        URIs: http://security.ubuntu.com/ubuntu/
        Suites: noble-security
        Components: main restricted universe
        Architectures: amd64
            
        Types: deb
        URIs: http://archive.ubuntu.com/ubuntu/
        Suites: noble-updates
        Components: main restricted universe
        Architectures: amd64
           
        Types: deb
        URIs: http://azure.ports.ubuntu.com/ubuntu-ports/
        Suites: noble
        Components: main restricted multiverse universe
        Architectures: arm64
         
        Types: deb
        URIs: http://azure.ports.ubuntu.com/ubuntu-ports/
        Suites: noble-updates
        Components: main restricted multiverse universe
        Architectures: arm64
        EOF
  
          sudo mv deb822sources /etc/apt/sources.list.d/ubuntu.sources
        else
          sudo mv config/crosscomp-sources.list /etc/apt/sources.list
        fi
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build with Makefile
      working-directory: docker/mingw
      env:
        REPO: ${{ github.repository_owner }}
        REV: ${{ github.sha }}
      run: |
        # 根据项目README，在Unix-like系统使用make
        make REPO=$REPO REV=$REV PLUGIN=true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shadowsocks-libev-windows
        path: docker/mingw/ss-libev-win-dist.tar.gz
