name: Build Windows Binaries

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build with Makefile
      working-directory: docker/mingw
      env:
        REPO: ${{ github.repository_owner }}
        REV: ${{ github.sha }}
      run: |
        # 根据项目README，在Unix-like系统使用make
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shadowsocks-libev-windows
        path: docker/mingw/ss-libev-win-dist.tar.gz
